config/routes.rb
Rails.application.routes.draw do
  
  
  # misc routes, may be candidates for removal
  get 'admin/index'
  resources :animal_types
  resources :breeds
  resources :shelter_types
  
  
  # routes for pets
  get 'pets/search' => 'pets#search', :as => :search
  get 'pets/:id/watch_list' => 'pets#watchlist', :as => :watchlist
  delete 'pets/:id/watch_list' => 'pets#watchlist_remove'
  resources :pets
  
  # routes for shelters
  get 'shelters/:id/hours' => 'shelters#hours', :as => :shelter_hours
  post 'shelters/:id/hours' => 'shelters#update_hours'
  resources :shelters

  # routes for users
  resources :users, :only => [:new, :create, :show]

  # routes for session  
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' #  performs login and authenticates password
  delete '/login' => 'session#destroy' # logout

  get '/admin' => 'admin#index' #admin controls

  root :to => "pets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shelter.rb
# == Schema Information
#
# Table name: shelters
#
#  id              :bigint(8)        not null, primary key
#  name            :string
#  postcode        :string
#  address         :string
#  suburb          :string
#  state           :string
#  shelter_type_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  image           :text
#  url             :text
#  phone           :string
#  email           :string
#  api_id          :bigint(8)
#

class Shelter < ApplicationRecord
  belongs_to :shelter_type
  
  has_many :pets
  has_many :users
  has_many :operating_hours, dependent: :destroy

  def image # Return default placeholder image if empty when requesting image
    result = read_attribute(:image)
    result.present? ? result : 'https://res.cloudinary.com/ddqzfx6t8/image/upload/v1531983865/no-image.jpg'
  end
end

app/models/shelter_type.rb
# == Schema Information
#
# Table name: shelter_types
#
#  id        :bigint(8)        not null, primary key
#  type_name :text
#

class ShelterType < ApplicationRecord
  has_many :shelters
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

  before_action :get_shelter, :only => [:show, :edit, :update, :hours, :update_hours]
  before_action :check_for_shelter_admin, :only => [:edit, :update, :hours]
  before_action :check_for_admin, :only => [:new, :create]

  def hours
    @hours = @shelter.operating_hours.order(:day_of_week)
    if @hours.length < 7
      days = @shelter.operating_hours.pluck(:day_of_week)
      # not all hours populated
      for i in (0).upto(6) #populate new hours for the shelter
        @shelter.operating_hours.create :day_of_week => i unless days.include? i
      end
    end
    #rotate so that it starts a "monday", by default starts "sunday"
    @hours = @shelter.operating_hours.order(:day_of_week).rotate
  end
  
  def update_hours
    #update each day in the hours params
    hours_params.keys.each do |day|
      day_num = Date::DAYNAMES.index(day.capitalize)
      @shelter.operating_hours.find_by(day_of_week: day_num).update hours_params[day]
    end
    
    redirect_to @shelter
  end

  def show
  end

  def index
    @shelters = Shelter.all
  end

  def edit
  end

  def update
    @shelter.update shelter_params
    redirect_to @shelter
  end

  def new
    @shelter = Shelter.new
  end

  def create
    @shelter = Shelter.create shelter_params
    redirect_to @shelter
  end


  private

  def shelter_params
    params.require(:shelter).permit(
      :name, 
      :postcode,
      :address,
      :suburb,
      :state,
      :shelter_type_id,
      :image,
      :url,
      :phone,
      :email
    )
  end

  def hours_params
    params.require(:hours).permit(
      :monday => {},
      :tuesday => {},
      :wednesday => {},
      :thursday => {},
      :friday => {},
      :saturday => {},
      :sunday => {}
    )
  end

  def get_shelter
    @shelter = Shelter.find params[:id]
  end

  def check_for_shelter_admin
    unless @current_user.present? && @current_user.shelter == @shelter
      redirect_to shelters_path
    end
  end
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/shelters/_form.html.erb
<%= form_for @shelter do |f| %>
  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  <% end %>
  
  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :postcode %>
    <%= f.text_field :postcode, :class => 'form-control' %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :address %>
    <%= f.text_field :address, :class => 'form-control' %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :suburb %>
    <%= f.text_field :suburb, :class => 'form-control' %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :state %>
    <%= f.text_field :state, :class => 'form-control' %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :shelter_type_id %>
    <%= f.select(:shelter_type_id, ShelterType.all.pluck(:type_name,:id), {}, { :class => 'form-control'}) %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :image %>
    <%= f.url_field :image, :class => 'form-control' %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :url , 'Website' %>
    <%= f.url_field :url, :class => 'form-control' %>
  <% end %>

  <%= content_tag :div, class: 'form-group' do %>
    <%= f.label :phone %>
    <%= f.text_field :phone, :class => 'form-control' %>
  <% end %>

  <%= content_tag :div, class: 'form-group inline' do %>
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control' %>
  <% end %>

  <%= f.submit :class => 'btn btn-primary'%>
<% end %>


<%
#  id              :bigint(8)        not null, primary key
#  name            :string
#  postcode        :string
#  address         :string
#  suburb          :string
#  state           :string
#  shelter_type_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  image           :text
#  url             :text
#  phone           :string
#  email           :string
%>

app/views/shelters/edit.html.erb
<%= content_tag :div, class: 'container card shadow-sm form' do %>
  <%= content_tag :div, class: 'card-body' do %>
    <%= content_tag :h2, "Edit #{@shelter.name}", class: 'card-title' %>
    <%= render partial: 'form' %>
  <% end %>
<% end %>

app/views/shelters/hours.html.erb
<div class="container card form">
  <div class="card-body">
    <%= form_tag(shelter_hours_path, method: "post") do %>
      <%= fields_for :hours, @hours do |hrs| %>  
        <% @hours.each do |h| %>
          <%= content_tag :div, class: 'form-group' do %>
            <%= hrs.label :hours, h.day_of_week %><br />
            <%= hrs.fields_for "#{h.day_of_week.downcase}", h do |day| %>
              <%= day.label :open, "Open" %>
              <%= day.time_field :open, class: 'form-control inline' %>
              <%= day.label :close, "close" %>
              <%= day.time_field :close, class: 'form-control inline' %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <%= submit_tag 'Update Hours', :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/shelters/index.html.erb
<div class="row">
<% @shelters.each do |s| %>
  <div class="col-md-4">
    <div class="card pet shadow-sm">
      <a class="cardlink" href="/shelters/<%= s.id %>"></a>        
      <div class="row pt-2 pl-4 pr-2">
        <div class="icon shelter"> </div>
        <div class="col">
          <div class="row"><h5 class="card-title"><%= s.name %></h5></div>
          <div class="row">
            <%= content_tag :p, s.shelter_type.type_name, :class => 'card-subtitle mb-2 text-muted' %>
          </div>
        </div>
      </div>
        <%= image_tag s.image, :class => 'card-img-bottom' %>
    </div>
  </div>
<% end %>
</div>

app/views/shelters/new.html.erb
<%= content_tag :div, class: 'container card shadow-sm form' do %>
  <%= content_tag :div, class: 'card-body' do %>
    <%= content_tag :h2, "Add Shelter", class: 'card-title' %>
    <%= render partial: 'form' %>
  <% end %>
<% end %>

app/views/shelters/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4"> <!-- Shelter Info Tile -->
      <div class="card">
        <div class="card-body">
          <div class="shelter-header">
            <%= image_tag @shelter.image %>
            <%= content_tag :h1, @shelter.name, class: 'card-title' %>
          </div>
            <%= content_tag :p, @shelter.shelter_type.type_name, class: "info" %>
            <p class="info">
              <%= @shelter.address %><br />
              <%= @shelter.suburb %> <%= @shelter.state %> <%= @shelter.postcode %>
            </p>
            <%= content_tag :p, class: "info"  do %>
              Ph: <%= link_to @shelter.phone, "tel:#{@shelter.phone}" %><br />
              Email: <%= link_to @shelter.email, "mailto:#{@shelter.email}" %><br />
              <%= link_to 'Website', @shelter.url %>
            <% end %>

            <%= content_tag :div, class: "info" do %>
              <%= content_tag :p, 'Opening Hours:' %>
              <ul class="no-list">
                <% @shelter.operating_hours.each do |hrs| %>
                  <% if hrs.open.present? %>
                    <%= content_tag :li do %>
                      <%= content_tag :div, "#{ hrs.day_of_week }:" %>
                      <%= content_tag :div, "#{ hrs.open.strftime '%l:%M %p' } - #{ hrs.close.strftime '%l:%M %p' }", class: 'align-right' %>
                    <% end %>
                  <% end %>
                <% end %>
              </ul>
            <% end %>
            
            
            

          <% if @current_user.present? && @current_user.shelter_id == @shelter.id %>
          <div class='controls'>
            <%= link_to 'Edit', edit_shelter_path, class: 'btn btn-secondary' %>
            <%= link_to 'Edit Hours', shelter_hours_path, class: 'btn btn-secondary' %>
            <%= link_to 'Add Pet', new_pet_path, class: 'btn btn-secondary' %>
          </div>
          <% end %>

        </div>
      </div> <!-- END Shelter Info Tile -->
    </div>
    <div class="col"> <!-- pets tiles -->
      <% @shelter.pets.each do |p| %>
      <div class="row mb-3">
        <div class="col-sm">      
          <div class="card pet shadow-sm">
            <a class="cardlink" href="/pets/<%= p.id %>"></a>
            <div class="row">
              <div class="thumb-container">
                <%= image_tag p.photos.first[:url], :class => 'thumbnail' %>
              </div>
              <div class="col-sm">
                <div class="row pt-2 pl-3 pr-2">
                  <div class="icon <%= p.animal_type.type_name.downcase %>"> </div>
                  <div class="col-sm">
                    <div class="row"><h5 class="card-title"><%= p.name %></h5></div>
                    <div class="row">
                      <%= content_tag :p, p.breed.name, :class => 'card-subtitle mb-2 text-muted' %>
                    </div>
                  </div>
                  <% if @current_user.present? && @current_user.shelter_id == @shelter.id %>
                    <%= link_to 'Remove', p, :method => 'delete', :class => "btn btn-light align-self-start ml-auto mr-3 remove" %>
                    <%= link_to 'Edit', edit_pet_path(p), :class => "btn btn-light align-self-start ml-auto mr-3 remove" %>
                  <% end %>
                </div>
                <div class="row">
                  <div class="col">
                    <%= content_tag :p, p.description, class: 'card-text' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div> 
</div>