config/routes.rb
Rails.application.routes.draw do
  
  
  # misc routes, may be candidates for removal
  get 'admin/index'
  resources :animal_types
  resources :breeds
  resources :shelter_types
  
  
  # routes for pets
  get 'pets/search' => 'pets#search', :as => :search
  get 'pets/:id/watch_list' => 'pets#watchlist', :as => :watchlist
  delete 'pets/:id/watch_list' => 'pets#watchlist_remove'
  resources :pets
  
  # routes for shelters
  get 'shelters/:id/hours' => 'shelters#hours', :as => :shelter_hours
  post 'shelters/:id/hours' => 'shelters#update_hours'
  resources :shelters

  # routes for users
  resources :users, :only => [:new, :create, :show]

  # routes for session  
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' #  performs login and authenticates password
  delete '/login' => 'session#destroy' # logout

  get '/admin' => 'admin#index' #admin controls

  root :to => "pets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/animal_types_controller.rb
class AnimalTypesController < ApplicationController
  before_action :check_for_admin
  before_action :get_animal_type, :only => [:show, :edit, :update]

  def index
    @animal_types = AnimalType.all
  end

  def create
    @animal_type = AnimalType.create animal_type_params
    redirect_to animal_types_path
  end

  def new
    @animal_type = AnimalType.new
  end

  def destroy
    AnimalType.find(params[:id]).destroy
    redirect_to animal_types_path
  end

  def show
    
  end
  
  def edit
    
  end


  private
    def animal_type_params
      params.require(:animal_type).permit(:type_name)
    end

    def get_animal_type
      @animal_type = AnimalType.find(params[:id])
    end
end

app/helpers/animal_types_helper.rb
module AnimalTypesHelper
end

app/views/animal_types/index.html.erb
<%= content_tag :h1, 'Animal Types' %>

<ul>
<% @animal_types.each do |at| %>
  <li>
    <%= link_to at.type_name, edit_animal_type_path(at) %>
    <%= link_to 'Delete', animal_type_path(at), :method => 'delete', :data => {:confirm => "Are you sure you want to delete #{ at.type_name }"} %>
 </li>
<% end %>
</ul>

app/views/animal_types/new.html.erb
<h1>AnimalTypes#new</h1>
<p>Find me in app/views/animal_types/new.html.erb</p>

app/views/animal_types/show.html.erb
<h1>AnimalTypes#show</h1>
<p>Find me in app/views/animal_types/show.html.erb</p>