config/routes.rb
Rails.application.routes.draw do
  
  
  # misc routes, may be candidates for removal
  get 'admin/index'
  resources :animal_types
  resources :breeds
  resources :shelter_types
  
  
  # routes for pets
  get 'pets/search' => 'pets#search', :as => :search
  get 'pets/:id/watch_list' => 'pets#watchlist', :as => :watchlist
  delete 'pets/:id/watch_list' => 'pets#watchlist_remove'
  resources :pets
  
  # routes for shelters
  get 'shelters/:id/hours' => 'shelters#hours', :as => :shelter_hours
  post 'shelters/:id/hours' => 'shelters#update_hours'
  resources :shelters

  # routes for users
  resources :users, :only => [:new, :create, :show]

  # routes for session  
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' #  performs login and authenticates password
  delete '/login' => 'session#destroy' # logout

  get '/admin' => 'admin#index' #admin controls

  root :to => "pets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shelter_types_controller.rb
class ShelterTypesController < ApplicationController
  before_action :check_for_admin
  before_action :get_shelter_type, :only => [:destroy, :show, :edit, :update]

  def index
    @shelter_types = ShelterType.all
  end

  def create
  end

  def new
  end

  def destroy
    @shelter_type.destroy
    redirect_to shelter_types_path
  end

  def show
  end

  private
  def get_shelter_type
    @shelter_type = ShelterType.find params[:id]
  end

  def shelter_type_params
    params.require(:shelter_type).permit(:type_name)
  end

end

app/helpers/shelter_types_helper.rb
module ShelterTypesHelper
end

app/views/shelter_types/index.html.erb
<%= content_tag :h1, 'Shelter Types' %>

<ul>
<% @shelter_types.each do |st| %>
  <li>
    <%= link_to st.type_name, edit_shelter_type_path(st) %>
    <%= link_to 'Delete', shelter_type_path(st), :method => 'delete', :data => {:confirm => "Are you sure you want to delete #{ st.type_name }"} %>
 </li>
<% end %>
</ul>

app/views/shelter_types/new.html.erb
<h1>ShelterTypes#new</h1>
<p>Find me in app/views/shelter_types/new.html.erb</p>

app/views/shelter_types/show.html.erb
<h1>ShelterTypes#show</h1>
<p>Find me in app/views/shelter_types/show.html.erb</p>