config/routes.rb
Rails.application.routes.draw do
  
  
  # misc routes, may be candidates for removal
  get 'admin/index'
  resources :animal_types
  resources :breeds
  resources :shelter_types
  
  
  # routes for pets
  get 'pets/search' => 'pets#search', :as => :search
  get 'pets/:id/watch_list' => 'pets#watchlist', :as => :watchlist
  delete 'pets/:id/watch_list' => 'pets#watchlist_remove'
  resources :pets
  
  # routes for shelters
  get 'shelters/:id/hours' => 'shelters#hours', :as => :shelter_hours
  post 'shelters/:id/hours' => 'shelters#update_hours'
  resources :shelters

  # routes for users
  resources :users, :only => [:new, :create, :show]

  # routes for session  
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' #  performs login and authenticates password
  delete '/login' => 'session#destroy' # logout

  get '/admin' => 'admin#index' #admin controls

  root :to => "pets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FureverApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'https://res.cloudinary.com/ddqzfx6t8/image/upload/v1531983461/furevr.favicon.png.png', :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-3 shadow-sm">
      <nav class="row pt-4">
        <div class="logo"></div>
        <div class="show-sm">
          <%= link_to '≫ Pets', pets_path %>
          <%= link_to '≫ Shelters', shelters_path %>
          <% if @current_user.present? %>
          <%= link_to '≫ Watch List', user_path(@current_user) %>
          <%= link_to '≫ Sign Out', login_path, :method => 'delete' %>
          <% else %>
          <%= link_to '≫ Sign Up', new_user_path %>
          <%= link_to '≫ Login', login_path %>
          <% end %>

          <% if @current_user.present? && @current_user.shelter_id.present? %>
            <%= link_to 'Manage', shelter_path(@current_user.shelter_id) %>
          <% end %>
        </div>
        <div class="col-sm hide-sm">
          <%= link_to 'Browse Pets', pets_path %>
          <span class="show-md">&nbsp;|&nbsp;</span>
          <%= link_to 'Browse Shelters', shelters_path %>
        </div>
        <div class="col-sm-1 hide-md"></div>
        <div class="col-sm hide-sm">
          <% if @current_user.present? %>
          <%= link_to 'Watch List', user_path(@current_user) %>
          <span class="show-md">&nbsp;|&nbsp;</span>
          <%= link_to 'Sign Out', login_path, :method => 'delete' %>
          <% else %>
          <%= link_to 'Sign Up', new_user_path %>
          <span class="show-md">&nbsp;|&nbsp;</span>
          <%= link_to 'Login', login_path %>
          <% end %>

          <%# if @current_user.present? && @current_user.admin? %>
            <%# link_to 'Admin Console', admin_path %>
          <%# end %>

          <% if @current_user.present? && @current_user.shelter_id.present? %>
            <%= link_to 'Manage', shelter_path(@current_user.shelter_id) %>
          <% end %>
        </div>
      </nav>
      <div class="slogan row">
      <h2>Open your home Furevr</h2></div>
      <%= render partial: 'search_bar' %>
    </header>
      <main class="container-fluid">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FureverApp</title>
    <%= favicon_link_tag 'https://res.cloudinary.com/ddqzfx6t8/image/upload/v1531983461/furevr.favicon.png.png', :rel => 'icon', :type =>  'image/png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="full-page d-flex justify-content-center align-items-center">
      <div class="signup shadow-sm">
        <header>
          <nav>
            <div class="logo"></div>
            <%= link_to 'Back', root_path, class: 'btn btn-primary' %>
          </nav>
          <div class="slogan">Open your home Furevr</div>
        </header>
        <main>
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>